import Head from "next/head";
import { PageLayout, Header, Text } from "@primer/react";
import styles from "./index.module.css";

// associates the dynamic name for the scoped class (generated by the CSS Modules pipeline)
// to the defined object keys
const contentWidthClasses = {
  small: styles.smallContent,
};

export default function DefaultLayout({
  children,
  metadata = {},
  contentWidth,
}) {
  const extraContentClassName = contentWidthClasses[contentWidth];

  return (
    <>
      <Head>
        <title>
          {metadata.title
            ? `${metadata.title} · Construindo Seu Futuro`
            : "Construindo Seu Futuro"}
        </title>

        {metadata.description && (
          <meta name="description" content={metadata.description} />
        )}
      </Head>

      <PageLayout.Header>
        <Header>
          <Header.Item full>
            <Header.Link href="/">Construindo Seu Futuro</Header.Link>
          </Header.Item>
          <Header.Item>
            <Header.Link href="/login">Login</Header.Link>
          </Header.Item>
          <Header.Item>
            <Header.Link href="/cadastro">Cadastre-se</Header.Link>
          </Header.Item>
        </Header>
      </PageLayout.Header>

      <PageLayout>
        <PageLayout.Content
          width={contentWidth}
          className={extraContentClassName}
        >
          {children}
        </PageLayout.Content>

        <PageLayout.Footer divider="line">
          <Text size="small">
            © {new Date().getFullYear()} Construindo Seu Futuro | Todos os direitos reservados.
          </Text>
        </PageLayout.Footer>
      </PageLayout>
    </>
  );
}
